figure1:
  - ngc1622_mom0.pdf
  - ngc1622_snr.pdf
  - ngc1622_mom1.pdf
  - ngc1622_chan.pdf
  - ngc1622_mom2.pdf
  - ngc1622_spec.pdf
figure2:
  - hcg16_meerkat_gbt_spec.pdf
  - hcg30_meerkat_gbt_spec.pdf
  - hcg31_meerkat_gbt_spec.pdf
  - hcg90_meerkat_gbt_spec.pdf
  - hcg91_meerkat_gbt_spec.pdf
  - hcg97_meerkat_gbt_spec.pdf
  - hcgs_meerkat_gbt_flux.pdf
  - hcg16_velocity_ra.pdf
  - hcg30_velocity_ra.pdf
  - hcg31_velocity_ra.pdf
  - hcg90_velocity_ra.pdf
  - hcg91_velocity_ra.pdf
  - hcg97_velocity_ra.pdf
  - hcg16_noise_specaxis.pdf
  - hcg30_noise_specaxis.pdf
  - hcg31_noise_specaxis.pdf
  - hcg90_noise_specaxis.pdf
  - hcg91_noise_specaxis.pdf
  - hcg97_noise_specaxis.pdf
  - hcg16_global_profile.pdf
  - hcg30_global_profile.pdf
  - hcg31_global_profile.pdf
  - hcg90_global_profile.pdf
  - hcg91_global_profile.pdf
  - hcg97_global_profile.pdf
  - hcg16_mom0_pbc_zoom.pdf
  - hcg30_mom0_pbc_zoom.pdf
  - hcg31_mom0_pbc_zoom.pdf
  - hcg90_mom0_pbc_zoom.pdf
  - hcg91_mom0_pbc_zoom.pdf
  - hcg97_mom0_pbc_zoom.pdf
  - hcg16_mom0_pbc_large.pdf
  - hcg30_mom0_pbc_large.pdf
  - hcg31_mom0_pbc_large.pdf
  - hcg90_mom0_pbc_large.pdf
  - hcg91_mom0_pbc_large.pdf
  - hcg97_mom0_pbc_large.pdf
  - hcg16_coldens_pbc_zoom.pdf
  - hcg30_coldens_pbc_zoom.pdf
  - hcg31_coldens_pbc_zoom.pdf
  - hcg90_coldens_pbc_zoom.pdf
  - hcg91_coldens_pbc_zoom.pdf
  - hcg97_coldens_pbc_zoom.pdf
  - hcg16_coldens_pbc_large.pdf
  - hcg30_coldens_pbc_large.pdf
  - hcg31_coldens_pbc_large.pdf
  - hcg90_coldens_pbc_large.pdf
  - hcg91_coldens_pbc_large.pdf
  - hcg97_coldens_pbc_large.pdf
  - hcg16_mom1_pbc_zoom.pdf
  - hcg30_mom1_pbc_zoom.pdf
  - hcg31_mom1_pbc_zoom.pdf
  - hcg90_mom1_pbc_zoom.pdf
  - hcg91_mom1_pbc_zoom.pdf
  - hcg97_mom1_pbc_zoom.pdf
  - hcg16_mom1_pbc_large.pdf
  - hcg30_mom1_pbc_large.pdf
  - hcg31_mom1_pbc_large.pdf
  - hcg90_mom1_pbc_large.pdf
  - hcg91_mom1_pbc_large.pdf
  - hcg97_mom1_pbc_large.pdf
  - hcg16_segmented_pv_view_mom0.pdf
  - hcg16_optical_hi.pdf
  - hcg30_optical_hi.pdf
  - hcg31_optical_hi.pdf
  - hcg90_optical_hi.pdf
  - hcg91_optical_hi.pdf
  - hcg97_optical_hi.pdf
  - hcg16_segmented_pv.pdf
  - hcg16_segmented_pv_vla.pdf
  - hcg16_chanmap142_pbc_zoom.pdf
  - hcg16_chanmap143_pbc_zoom.pdf
  - hcg16_chanmap144_pbc_zoom.pdf
  - hcg16_chanmap145_pbc_zoom.pdf
  - hcg16_chanmap146_pbc_zoom.pdf
  - hcg16_chanmap147_pbc_zoom.pdf
  - hcg16_chanmap148_pbc_zoom.pdf
  - hcg16_chanmap149_pbc_zoom.pdf
  - hcg16_chanmap150_pbc_zoom.pdf
  - hcg16_chanmap151_pbc_zoom.pdf
  - hcg16_chanmap152_pbc_zoom.pdf
  - hcg16_chanmap153_pbc_zoom.pdf
  - hcg16_chanmap154_pbc_zoom.pdf
  - hcg16_chanmap155_pbc_zoom.pdf
  - hcg16_chanmap156_pbc_zoom.pdf
  - hcg16_chanmap157_pbc_zoom.pdf
  - hcg16_chanmap158_pbc_zoom.pdf
  - hcg16_chanmap159_pbc_zoom.pdf
  - hcg16_chanmap160_pbc_zoom.pdf
  - hcg16_chanmap161_pbc_zoom.pdf
  - hcg16_chanmap162_pbc_zoom.pdf
  - hcg16_chanmap163_pbc_zoom.pdf
  - hcg16_chanmap164_pbc_zoom.pdf
  - hcg16_chanmap165_pbc_zoom.pdf
  - hcg16_chanmap166_pbc_zoom.pdf
  - hcg16_chanmap167_pbc_zoom.pdf
  - hcg16_chanmap168_pbc_zoom.pdf
  - hcg16_chanmap169_pbc_zoom.pdf
  - hcg16_chanmap170_pbc_zoom.pdf
  - hcg16_chanmap171_pbc_zoom.pdf
  - hcg16_chanmap172_pbc_zoom.pdf
  - hcg16_chanmap173_pbc_zoom.pdf
  - hcg16_chanmap174_pbc_zoom.pdf
  - hcg16_chanmap175_pbc_zoom.pdf
  - hcg16_chanmap176_pbc_zoom.pdf
  - hcg16_chanmap177_pbc_zoom.pdf
  - hcg16_chanmap178_pbc_zoom.pdf
  - hcg16_chanmap179_pbc_zoom.pdf
  - hcg16_chanmap180_pbc_zoom.pdf
  - hcg16_chanmap181_pbc_zoom.pdf
  - hcg16_chanmap182_pbc_zoom.pdf
  - hcg16_chanmap183_pbc_zoom.pdf
  - hcg16_chanmap184_pbc_zoom.pdf
  - hcg16_chanmap185_pbc_zoom.pdf
  - hcg16_chanmap186_pbc_zoom.pdf
  - hcg16_chanmap187_pbc_zoom.pdf
  - hcg16_chanmap188_pbc_zoom.pdf
  - hcg16_chanmap189_pbc_zoom.pdf
  - hcg16_chanmap190_pbc_zoom.pdf
  - hcg16_chanmap191_pbc_zoom.pdf
  - hcg16_chanmap192_pbc_zoom.pdf
  - hcg16_chanmap193_pbc_zoom.pdf
  - hcg16_chanmap194_pbc_zoom.pdf
  - hcg16_chanmap195_pbc_zoom.pdf
  - hcg16_chanmap196_pbc_zoom.pdf
  - hcg16_chanmap197_pbc_zoom.pdf
  - hcg16_chanmap198_pbc_zoom.pdf
  - hcg16_chanmap199_pbc_zoom.pdf
  - hcg16_chanmap200_pbc_zoom.pdf
  - hcg16_chanmap201_pbc_zoom.pdf
  - hcg16_chanmap202_pbc_zoom.pdf
  - hcg16_chanmap203_pbc_zoom.pdf
  - hcg16_chanmap204_pbc_zoom.pdf
  - hcg16_chanmap205_pbc_zoom.pdf
  - hcg16_chanmap206_pbc_zoom.pdf
  - hcg16_chanmap207_pbc_zoom.pdf
  - hcg16_chanmap208_pbc_zoom.pdf
  - hcg16_chanmap209_pbc_zoom.pdf
  - hcg16_chanmap210_pbc_zoom.pdf
  - hcg16_chanmap211_pbc_zoom.pdf
  - hcg16_chanmap212_pbc_zoom.pdf
  - hcg16_chanmap213_pbc_zoom.pdf
  - hcg16_chanmap214_pbc_zoom.pdf
  - hcg16_chanmap215_pbc_zoom.pdf
  - hcg16_chanmap216_pbc_zoom.pdf
  - hcg16_chanmap217_pbc_zoom.pdf
  - hcg16_chanmap218_pbc_zoom.pdf
  - hcg16_chanmap219_pbc_zoom.pdf
  - hcg16_chanmap220_pbc_zoom.pdf
  - hcg16_chanmap221_pbc_zoom.pdf
  - hcg16_chanmap222_pbc_zoom.pdf
  - hcg16_chanmap223_pbc_zoom.pdf
  - hcg16_chanmap224_pbc_zoom.pdf
  - hcg16_chanmap225_pbc_zoom.pdf
  - hcg16_chanmap226_pbc_zoom.pdf
  - hcg16_chanmap227_pbc_zoom.pdf
  - hcg16_chanmap228_pbc_zoom.pdf
  - hcg16_chanmap229_pbc_zoom.pdf
  - hcg16_chanmap230_pbc_zoom.pdf
  - hcg16_chanmap231_pbc_zoom.pdf
  - hcg16_chanmap232_pbc_zoom.pdf
  - hcg16_chanmap233_pbc_zoom.pdf
  - hcg16_chanmap234_pbc_zoom.pdf
