figure1:
  - ngc1622_column_density.pdf
  - ngc1622_snr.pdf
  - ngc1622_mom1.pdf
  - ngc1622_chan.pdf
  - ngc1622_mom2.pdf
  - ngc1622_spec.pdf
figure2:
  - hcg16_meerkat_gbt_spec.pdf
  - hcg30_meerkat_gbt_spec.pdf
  - hcg31_meerkat_gbt_spec.pdf
  - hcg90_meerkat_gbt_spec.pdf
  - hcg91_meerkat_gbt_spec.pdf
  - hcg97_meerkat_gbt_spec.pdf
  - hcgs_meerkat_gbt_flux.pdf
  - hcg16_velocity_ra.pdf
  - hcg30_velocity_ra.pdf
  - hcg31_velocity_ra.pdf
  - hcg90_velocity_ra.pdf
  - hcg91_velocity_ra.pdf
  - hcg97_velocity_ra.pdf
  - hcg16_noise_specaxis.pdf
  - hcg30_noise_specaxis.pdf
  - hcg31_noise_specaxis.pdf
  - hcg90_noise_specaxis.pdf
  - hcg91_noise_specaxis.pdf
  - hcg97_noise_specaxis.pdf
  - hcg16_global_profile.pdf
  - hcg30_global_profile.pdf
  - hcg31_global_profile.pdf
  - hcg90_global_profile.pdf
  - hcg91_global_profile.pdf
  - hcg97_global_profile.pdf
  - hcg16_mom0_pbc_zoom.pdf
  - hcg30_mom0_pbc_zoom.pdf
  - hcg31_mom0_pbc_zoom.pdf
  - hcg90_mom0_pbc_zoom.pdf
  - hcg91_mom0_pbc_zoom.pdf
  - hcg97_mom0_pbc_zoom.pdf
  - hcg16_mom0_pbc_large.pdf
  - hcg30_mom0_pbc_large.pdf
  - hcg31_mom0_pbc_large.pdf
  - hcg90_mom0_pbc_large.pdf
  - hcg91_mom0_pbc_large.pdf
  - hcg97_mom0_pbc_large.pdf
  - hcg16_coldens_pbc_zoom.pdf
  - hcg30_coldens_pbc_zoom.pdf
  - hcg31_coldens_pbc_zoom.pdf
  - hcg90_coldens_pbc_zoom.pdf
  - hcg91_coldens_pbc_zoom.pdf
  - hcg97_coldens_pbc_zoom.pdf
  - hcg16_coldens_pbc_large.pdf
  - hcg30_coldens_pbc_large.pdf
  - hcg31_coldens_pbc_large.pdf
  - hcg90_coldens_pbc_large.pdf
  - hcg91_coldens_pbc_large.pdf
  - hcg97_coldens_pbc_large.pdf
  - hcg16_mom1_pbc_zoom.pdf
  - hcg30_mom1_pbc_zoom.pdf
  - hcg31_mom1_pbc_zoom.pdf
  - hcg90_mom1_pbc_zoom.pdf
  - hcg91_mom1_pbc_zoom.pdf
  - hcg97_mom1_pbc_zoom.pdf
  - hcg16_mom1_pbc_large.pdf
  - hcg30_mom1_pbc_large.pdf
  - hcg31_mom1_pbc_large.pdf
  - hcg90_mom1_pbc_large.pdf
  - hcg91_mom1_pbc_large.pdf
  - hcg97_mom1_pbc_large.pdf
  - hcg16_segmented_pv_view_mom0.pdf
  - hcg16_segmented_pv.pdf
  - hcg16_segmented_pv_vla.pdf
  - hcg16_optical_mom0.pdf
  - hcg30_optical_mom0.pdf
  - hcg31_optical_mom0.pdf
  - hcg90_optical_mom0.pdf
  - hcg91_optical_mom0.pdf
  - hcg97_optical_mom0.pdf
  - hcg16_chanmap170_pbc_zoom.pdf
  - hcg16_chanmap171_pbc_zoom.pdf
